name: Google Analytics
description: Adds tracking of website traffic using Google Analytics and Google Tag Manager. Requires a Google Tag Manager ID.
install:
  - google_tag
  - klaro
input:
  property_id:
    data_type: string
    description: "The Google Tag, in the form of GT-xxxxxx, G-xxxxxxxx, AW-xxxxxxxxx, GTM-xxxxxxxx or DC-xxxxxxxx."
    prompt:
      method: ask
      arguments:
        question: "Enter the Google Tag ID for tracking. This ID is unique to each site you want to track separately, and must be in the form of GT-xxxxxx, G-xxxxxxxx, AW-xxxxxxxxx, GTM-xxxxxxxx or DC-xxxxxxxx."
    form:
      '#type': 'textfield'
      '#title': 'Google Tag ID'
      '#description': "The Google Tag ID for tracking. This ID is unique to each site you want to track separately, and must be in the form of GT-xxxxxx, G-xxxxxxxx, AW-xxxxxxxxx, GTM-xxxxxxxx or DC-xxxxxxxx."
    default:
      source: value
      value: ''
config:
  strict: false
  import:
    google_tag: '*'
    klaro: '*'
  actions:
    google_tag.settings:
      simpleConfigUpdate:
        default_google_tag_entity: drupal
    google_tag.container.drupal:
      set:
        property_name: tag_container_ids
        value:
          - ${property_id}
    klaro.klaro_app.ga:
      enable: []
    klaro.klaro_app.gtm:
      enable: []
    klaro.settings:
      simpleConfigUpdate:
        dialog_mode: notice
        auto_decorate_final_html: true
        library.group_by_purpose: true
    user.role.anonymous:
      grantPermission: 'use klaro'
    user.role.authenticated:
      grantPermission: 'use klaro'
extra:
  project_browser:
    tasks:
      - route_name: google_tag.settings_form
        text: Configure
