version: 2
registries:
  jfrog:
    type: composer-repository
    url: https://jfrog.ais.acquia.io
    username: github_dependabot_token
    password: ${{secrets.JFROG_GITHUB_DEPENDABOT_TOKEN}}
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  pull-request-branch-name:
    separator: "-"
  groups:
    github-actions:
      patterns:
      - "*"
  ignore:
  - update-types:
    - version-update:semver-major
  - dependency-name: "*"
- package-ecosystem: composer
  directory: /
  schedule:
    interval: weekly
  registries:
  - jfrog
  pull-request-branch-name:
    separator: "-"
  groups:
    composer:
      patterns:
      - "*"
  ignore:
  - update-types:
    - version-update:semver-major
  - dependency-name: "*"
- package-ecosystem: composer
  directory: /docroot/profiles/custom/acquia_drupal_cms_installer
  schedule:
    interval: weekly
  registries:
  - jfrog
  pull-request-branch-name:
    separator: "-"
  groups:
    composer:
      patterns:
      - "*"
  ignore:
  - update-types:
    - version-update:semver-major
  - dependency-name: "*"
