facet.widget.config.tagify:
  type: facet.widget.default_config
  label: 'Tagify widget configuration'
  mapping:
    match_operator:
      type: string
      label: 'Autocomplete matching'
    max_items:
      type: integer
      label: 'Number of results'
    placeholder:
      type: label
      label: 'Placeholder'
