name: Config Language Lock
type: module
description: Locks configuration language to an independently configured language.
package: Multilingual
core_version_requirement: ^11.2 || ^12

# Information added by Drupal.org packaging script on 2026-09-12
version: '1.0.2'
project: 'config_language_lock'
datestamp: 1789203645
