config_language_lock.settings:
  title: 'Configuration language'
  description: 'Configure a global configuration language for the site.'
  route_name: config_language_lock.settings
  parent: system.admin_config_regional
  weight: 35
