<?php

/**
 * @file
 * Contains hook implementations for Drupal CMS's installer theme.
 */

declare(strict_types=1);

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\File\FileUrlGeneratorInterface;
use Drupal\Core\Language\LanguageInterface;
use Drupal\Core\Language\LanguageManager;
use Drupal\drupal_cms_installer\Form\SiteNameForm;

/**
 * Implements template_preprocess_install_page().
 *
 * @phpstan-param array<string, mixed> $variables
 */
function drupal_cms_installer_theme_preprocess_install_page(array &$variables): void {
  global $base_url;

  $theme_path = \Drupal::theme()->getActiveTheme()->getPath();
  $variables['theme_path'] = \Drupal::service(FileUrlGeneratorInterface::class)
    ->generateString($theme_path);

  global $install_state;

  // Most screens get a decorative artwork added to the side.
  $pattern = match ($install_state['active_task']) {
    'install_settings_form', 'install_import_translations', 'install_finish_translations' => 'settings',
    SiteNameForm::class, 'drupal_cms_installer_almost_ready' => 'name',
    'install_configure_form' => 'account',
    'install_profile_modules' => 'recipes',
    default => NULL,
  };
  $variables['pattern'] = $pattern ? ['#theme' => 'step_svg', '#id' => $pattern] : [];

  // Only show the language switcher in the early installer.
  // @see install_state_defaults()
  if ($install_state['base_system_verified']) {
    return;
  }

  $variables['active_langcode'] = $install_state['parameters']['langcode'];
  $variables['languages'] = [];
  foreach (LanguageManager::getStandardLanguageList() as $langcode => $language) {
    $query = ['langcode' => $langcode] + $install_state['parameters'];

    // Pass the language's native name to the template, along with its
    // direction (if defined).
    $variables['languages'][$langcode] = [
      'name' => $language[1],
      'direction' => $language[2] ?? LanguageInterface::DIRECTION_LTR,
      'url' => $base_url . '/core/install.php?' . UrlHelper::buildQuery($query),
    ];
  }
}

/**
 * Implements hook_theme().
 *
 * @phpstan-return array<string, array<string, mixed>>
 */
function drupal_cms_installer_theme_theme(): array {
  return [
    'step_svg' => [
      'variables' => [
        'id' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter() for installer_site_name_form.
 *
 * @phpstan-param array<string, mixed> $form
 */
function drupal_cms_installer_theme_form_installer_site_name_form_alter(array &$form): void {
  $form['help'] = [
    '#prefix' => '<p class="cms-installer__subhead">',
    '#markup' => t('You can change this later.'),
    '#suffix' => '</p>',
    '#weight' => -100,
  ];
  $form['site_name'] += [
    '#prefix' => '<div class="cms-installer__form-group">',
    '#suffix' => '</div>',
  ];
  $form['actions']['submit']['#attributes']['class'] = ['button--next'];
}

/**
 * Implements hook_form_FORM_ID_alter() for installer_recipes_form.
 *
 * @phpstan-param array<string, mixed> $form
 */
function drupal_cms_installer_theme_form_installer_site_template_form_alter(array &$form): void {
  $form['help'] = [
    '#prefix' => '<p class="cms-installer__subhead">',
    '#markup' => t("Site templates provide a starting point with styling and features already included. You can customize the look and feel and add new features using Drupal's powerful extensibility."),
    '#suffix' => '</p>',
    '#weight' => -100,
  ];
  $form['add_ons'] += [
    '#prefix' => '<div class="cms-installer__form-group">',
    '#suffix' => '</div>',
  ];
  $form['actions']['submit']['#attributes']['class'] = ['button--next'];
}

/**
 * Implements template_preprocess_form_element() for site template choices.
 *
 * @phpstan-param array<string, mixed> $variables
 */
function drupal_cms_installer_theme_preprocess_form_element(array &$variables, string $hook): void {
  if ($hook !== 'form_element__site_template') {
    return;
  }

  /** @var \Drupal\drupal_cms_installer\SiteTemplate $recipe */
  $recipe = $variables['element']['item'];
  $variables['screenshot'] = $recipe->getScreenshot();
  // Open all links in a new tab.
  foreach ($recipe->links as $link) {
    $link->getUrl()->setOption('attributes', ['target' => '_blank']);
  }
  $variables['links'] = $recipe->links;
  $variables['price'] = $recipe->price;
  $variables['purchase_url'] = $recipe->purchaseUrl;
  $variables['creator'] = $recipe->creator;

  $variables['name'] = $variables['element']['#title'];
  $variables['id'] = $variables['element']['#id'];
}

/**
 * Implements hook_form_FORM_ID_alter() for install_settings_form.
 *
 * @phpstan-param array<string, mixed> $form
 */
function drupal_cms_installer_theme_form_install_settings_form_alter(array &$form): void {
  $form['help'] = [
    '#prefix' => '<p class="cms-installer__subhead">',
    '#markup' => t("You don't need to change anything here unless you want to use a different database type."),
    '#suffix' => '</p>',
    '#weight' => -50,
  ];
  $form['driver']['#type'] = 'select';
}

/**
 * Implements hook_form_FORM_ID_alter() for install_configure_form.
 *
 * @phpstan-param array<string, mixed> $form
 */
function drupal_cms_installer_theme_form_install_configure_form_alter(array &$form): void {
  $form['#title'] = t('Create your account');

  $form['help'] = [
    '#prefix' => '<p class="cms-installer__subhead">',
    '#markup' => t('Creating an account allows you to log in to your site.'),
    '#suffix' => '</p>',
    '#weight' => -40,
  ];

  // Use isset() to guard against the possibility that core will change the
  // structure of this form in a minor release.
  if (isset($form['admin_account']['account']['name'])) {
    $form['admin_account']['account']['mail'] += [
      '#prefix' => '<div class="cms-installer__form-group">',
      '#suffix' => '</div>',
    ];
  }
  if (isset($form['admin_account']['account']['pass'])) {
    $form['admin_account']['account']['pass'] += [
      '#prefix' => '<div class="cms-installer__form-group">',
      '#suffix' => '</div>',
    ];
  }
  $form['actions']['submit']['#value'] = t('Finish');
}
