name: 'Acquia Starter Kit Remote Video'
description: 'Provides a Remote Video media type and related configuration.'
type: 'Media type'
recipes:
  - core/recipes/remote_video_media_type
  - core/recipes/tags_taxonomy
install:
  # Contrib
  - acquia_starterkit_core
  - field_group
config:
  # If the active config doesn't match what's in the recipe config, we can
  # assume that Remote Video already exist or site owner has made some
  # tweaks to these configs.
  strict: false
  import:
    field_group: '*'
  actions:
    core.entity_form_display.media.remote_video.default:
      simpleConfigUpdate:
        third_party_settings:
          field_group:
            group_taxonomy:
              children:
                - field_categories
                - field_tags
              label: Taxonomy
              region: content
              parent_name: ''
              weight: 4
              format_type: fieldset
              format_settings:
                classes: ''
                id: ''
                description: ''
                required_fields: true
        content:
          created:
            type: datetime_timestamp
            weight: 7
            region: content
            settings: { }
            third_party_settings: { }
          field_media_oembed_video:
            type: oembed_textfield
            weight: 1
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: { }
          field_categories:
            type: options_select
            weight: 3
            region: content
            settings: { }
            third_party_settings: { }
          field_tags:
            type: entity_reference_autocomplete_tags
            weight: 4
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: { }
          langcode:
            type: language_select
            weight: 2
            region: content
            settings:
              include_locked: true
            third_party_settings: { }
          name:
            type: string_textfield
            weight: 0
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: { }
          translation:
            weight: 8
            region: content
            settings: { }
            third_party_settings: { }
          uid:
            type: entity_reference_autocomplete
            weight: 6
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: { }
        hidden:
          path: true
          status: true
    core.entity_form_display.media.remote_video.media_library:
      simpleConfigUpdate:
        third_party_settings:
          field_group:
            group_taxonomy:
              children:
                - field_categories
                - field_tags
              label: Taxonomy
              region: content
              parent_name: ''
              weight: 4
              format_type: fieldset
              format_settings:
                classes: ''
                id: ''
                description: ''
                required_fields: true
        content:
          name:
            type: string_textfield
            weight: 0
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: { }
          field_media_oembed_video:
            type: oembed_textfield
            weight: 1
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: { }
          field_categories:
            type: options_select
            weight: 3
            region: content
            settings: { }
            third_party_settings: { }
          field_tags:
            type: entity_reference_autocomplete_tags
            weight: 4
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: { }
        hidden:
          created: true
          path: true
          status: true
          uid: true
    core.entity_view_display.media.remote_video.embedded:
      simpleConfigUpdate:
        content:
          field_media_oembed_video:
            type: oembed
            label: visually_hidden
            settings:
              max_width: 960
              max_height: 540
            third_party_settings: { }
            weight: 0
            region: content
        hidden:
          created: true
          field_categories: true
          field_tags: true
          name: true
          search_api_excerpt: true
          thumbnail: true
          uid: true
    media.type.remote_video:
      setThirdPartySettings:
        - module: acquia_starterkit_core
          key: roles_permissions
          value:
            content_author:
              grant_permissions:
                - 'create remote_video media'
                - 'edit own remote_video media'
                - 'delete own remote_video media'
            content_editor:
              grant_permissions:
                - 'create remote_video media'
                - 'edit own remote_video media'
                - 'delete own remote_video media'
                - 'edit any remote_video media'
                - 'delete any remote_video media'
