<?php

/**
 * @file
 * Acquia Trials Cloud Platform module.
 */

/**
 * Implements hook_theme().
 */
function acquia_trials_cloud_platform_theme(): array {
  $subscription_id = getenv('AH_APPLICATION_UUID') ?: '';
  $cta_url = $subscription_id !== ''
    ? 'https://bar.com/' . $subscription_id
    : 'https://foo.com';

  return [
    'acquia_trials_cloud_platform' => [
      'variables' => [
        'features' => [],
        'cta_url' => $cta_url,
      ],
      'template' => 'acquia-trials-cloud-platform',
    ],
  ];
}
