field.formatter.settings.altcha_obfuscated_email:
  type: mapping
  label: 'ALTCHA Obfuscated email settings'
  mapping:
    reveal_text_override:
      type: label
      label: 'Reveal text override'
      translation context: 'altcha_obfuscate'

field.formatter.settings.altcha_obfuscated_string:
  type: mapping
  label: 'ALTCHA Obfuscated string settings'
  mapping:
    reveal_text_override:
      type: label
      label: 'Reveal text override'
      translation context: 'altcha_obfuscate'

field.formatter.settings.altcha_obfuscated_telephone:
  type: mapping
  label: 'ALTCHA Obfuscated telephone settings'
  mapping:
    reveal_text_override:
      type: label
      label: 'Reveal text override'
      translation context: 'altcha_obfuscate'
